// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type proxyCfg struct {
	_             structs.HostLayout
	RuleCount     uint32
	DefaultAction uint32
	TcpRelayPort  uint32
	UdpRelayPort  uint32
	LogLevel      uint32
}

type proxyDstinfo struct {
	_         structs.HostLayout
	Ip        uint32
	Port      uint16
	Connected uint16
	Pid       uint32
	RuleOrd   uint32
	Comm      [16]uint8
}

type proxyRule struct {
	_        structs.HostLayout
	Ip       uint32
	Mask     uint32
	PortLo   uint16
	PortHi   uint16
	Ord      uint32
	Name     [64]uint8
	NameLen  uint8
	Proto    uint8
	Action   uint8
	Enabled  uint8
	Wildcard uint8
	_        [3]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	proxyMapCfgMap          = "cfg_map"
	proxyMapEvents          = "events"
	proxyMapPending         = "pending"
	proxyMapRedirsTcp       = "redirs_tcp"
	proxyMapRedirsUdp       = "redirs_udp"
	proxyMapRules           = "rules"
	proxyMapStats           = "stats"
	proxyProgConnect4Prog   = "connect4_prog"
	proxyProgSendmsg4Prog   = "sendmsg4_prog"
	proxyProgSockopsProg    = "sockops_prog"
	proxyProgUdpSendmsgProg = "udp_sendmsg_prog"
)

// loadProxy returns the embedded CollectionSpec for proxy.
func loadProxy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProxyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load proxy: %w", err)
	}

	return spec, err
}

// loadProxyObjects loads proxy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*proxyObjects
//	*proxyPrograms
//	*proxyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProxyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProxy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// proxySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxySpecs struct {
	proxyProgramSpecs
	proxyMapSpecs
	proxyVariableSpecs
}

// proxyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxyProgramSpecs struct {
	Connect4Prog   *ebpf.ProgramSpec `ebpf:"connect4_prog"`
	Sendmsg4Prog   *ebpf.ProgramSpec `ebpf:"sendmsg4_prog"`
	SockopsProg    *ebpf.ProgramSpec `ebpf:"sockops_prog"`
	UdpSendmsgProg *ebpf.ProgramSpec `ebpf:"udp_sendmsg_prog"`
}

// proxyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxyMapSpecs struct {
	CfgMap    *ebpf.MapSpec `ebpf:"cfg_map"`
	Events    *ebpf.MapSpec `ebpf:"events"`
	Pending   *ebpf.MapSpec `ebpf:"pending"`
	RedirsTcp *ebpf.MapSpec `ebpf:"redirs_tcp"`
	RedirsUdp *ebpf.MapSpec `ebpf:"redirs_udp"`
	Rules     *ebpf.MapSpec `ebpf:"rules"`
	Stats     *ebpf.MapSpec `ebpf:"stats"`
}

// proxyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type proxyVariableSpecs struct {
}

// proxyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyObjects struct {
	proxyPrograms
	proxyMaps
	proxyVariables
}

func (o *proxyObjects) Close() error {
	return _ProxyClose(
		&o.proxyPrograms,
		&o.proxyMaps,
	)
}

// proxyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyMaps struct {
	CfgMap    *ebpf.Map `ebpf:"cfg_map"`
	Events    *ebpf.Map `ebpf:"events"`
	Pending   *ebpf.Map `ebpf:"pending"`
	RedirsTcp *ebpf.Map `ebpf:"redirs_tcp"`
	RedirsUdp *ebpf.Map `ebpf:"redirs_udp"`
	Rules     *ebpf.Map `ebpf:"rules"`
	Stats     *ebpf.Map `ebpf:"stats"`
}

func (m *proxyMaps) Close() error {
	return _ProxyClose(
		m.CfgMap,
		m.Events,
		m.Pending,
		m.RedirsTcp,
		m.RedirsUdp,
		m.Rules,
		m.Stats,
	)
}

// proxyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyVariables struct {
}

// proxyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProxyObjects or ebpf.CollectionSpec.LoadAndAssign.
type proxyPrograms struct {
	Connect4Prog   *ebpf.Program `ebpf:"connect4_prog"`
	Sendmsg4Prog   *ebpf.Program `ebpf:"sendmsg4_prog"`
	SockopsProg    *ebpf.Program `ebpf:"sockops_prog"`
	UdpSendmsgProg *ebpf.Program `ebpf:"udp_sendmsg_prog"`
}

func (p *proxyPrograms) Close() error {
	return _ProxyClose(
		p.Connect4Prog,
		p.Sendmsg4Prog,
		p.SockopsProg,
		p.UdpSendmsgProg,
	)
}

func _ProxyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed proxy_x86_bpfel.o
var _ProxyBytes []byte
